name: "godot-ci export"
on:
  push:
    branches:
      - main

env:
  GODOT_VERSION: 4.1.2
  EXPORT_NAME: SmashEm
  
jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      
      - name: Build
        id: build
        uses: manleydev/build-godot-action@v1.5.0
        with:
          name: $EXPORT_NAME.exe
          preset: "Windows Desktop"
          debugMode: "true"

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: $EXPORT_NAME
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}

