name: "godot-ci export"
on:
  push:
    branches:
      - main

env:
  GODOT_VERSION: 4.1.2
  EXPORT_NAME: SmashEm
  
jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1.2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      
      - name: Get current tag
        id: current-tag
        uses: WyriHaximus/github-action-get-previous-tag@v1.3.0
        with:
          fallback: 0
          prefix: v

      - name: Increase tag version
        id: next-tag
        uses: WyriHaximus/github-action-next-semvers@v1.2.1
        with:
          version: ${{ steps.current-tag.outputs.tag }}
          strict: true
      
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          cp -a /root/.local/share/godot/templates/. ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          godot -v --headless --export-release "Windows Desktop" build/windows/$EXPORT_NAME.exe
          pwd
          ls
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-${{ steps.semvers.outputs.v_major }}
          path: build/windows/
          if-no-files-found: error
      
      - name: 'Create new milestone'
        id: createmilestone
        uses: "WyriHaximus/github-action-create-milestone@v1"
        with:
          title: ${{ steps.semvers.outputs.v_major }}
